import AntdProvider from '@/components/AntdProvider'
import QueryProvider from '@/components/QueryProvider'
import type { Metadata } from 'next'
import { PropsWithChildren, Suspense } from 'react'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout(props: PropsWithChildren) {
  return (
    <html lang='en'>
      <body>
        <Suspense fallback={<div>Loading...</div>}>
          <QueryProvider>
            <AntdProvider>{props.children}</AntdProvider>
          </QueryProvider>
        </Suspense>
      </body>
    </html>
  )
}
